### ISSUE TITLE
CLI

### ISSUE THREAD

**Issue by f2prateek** [apex/log#15]
I've been using this to prettify tailing logs from production (similar to the [bunyan cli](https://github.com/trentm/node-bunyan#cli-usage)). Worth adding to the main project?

```go
package main

import (
	"bufio"
	"encoding/json"
	"os"

	"github.com/apex/log"
	"github.com/apex/log/handlers/text"
)

func main() {
	logger := text.New(os.Stdout)
	scanner := bufio.NewScanner(os.Stdin)
	for scanner.Scan() {
		text := scanner.Text()
		e := log.Entry{}
		if err := json.Unmarshal([]byte(text), &e); err != nil {
			panic(err)
		}
		logger.HandleLog(&e)
	}

	if err := scanner.Err(); err != nil {
		panic(err)
	}
}
```

**Comment by tj** [comment]
nice! Yeah maybe, I'm not sure how much utility it would have for the average case, mostly because I don't know if there is an average case haha. I'm using CloudWatch Logs, not really because I want to (it sucks) but you're kind of stuck with Lambda, so I'll have to parse the JSON from there and ship it onward

**Comment by f2prateek** [comment]
makes sense! I'll close this for now, can always re-open if we see more requests for it.
