### ISSUE TITLE
Debug(), Error() etc. should accept an interface instead of string

### ISSUE THREAD

**Issue by cleung2010** [apex/log#26]
A lot of the times I want to simply pass in the error to `Error()` (or similar functions) which works on [Sirupsen/logrus](https://github.com/Sirupsen/logrus), but now that I am trying to switch to `apex/log` it breaks all those cases.

```go
if err != nil {
  log.Error(err) // This is now broken
}

// Instead I have to do this
if err != nil {
  log.Errorf("%s", err) // or log.Error(err.Error()) which is not as clean
}
```

**Comment by tj** [comment]
The reason it's just strings is because (I believe) all the errors should be actionable and metrics-friendly. 

The `Error()` string is just a label, for example something like: `a.Log.WithError(err).Error("error fetching state")`. This way you see "error fetching state" in Kibana or other dashboards, not many unbounded messages that may be part of `err.String()`, which to me goes against structured logging.

Hope that makes sense!
