### ISSUE TITLE
Implement the io.Writer interface?

### ISSUE THREAD

**Issue by matthewmueller** [apex/log#42]
Would make stuff like this a bit easier:

```go
go io.Copy(log.Info, command.Stdout)
go io.Copy(log.Error, command.Stderr)
```

I guess it'd have to be something like else like:

```go
go io.Copy(log.InfoWriter(), command.Stdout)
go io.Copy(log.ErrorWriter(), command.Stderr)
```

**Comment by tj** [comment]
I decided not to go with io.Writer since it's technically safe to do partial writes to a io.Writer. It's more for textual/binary streams (say writing half an event) than something like events which have to be whole.

It might still be cool to support it my default with the logfmt-ish style output or something, but I think i'd still rather do `log.SetHandler(logfmt.New(os.Stdout))`

**Comment by matthewmueller** [comment]
ahh right that makes sense! might make sense to just be a small wrapper then. basically just looking for a good way to stream stderr to these handlers.
